from .event_bus import EventBus
from .events import (
    EventType,
    OrderAcceptedEvent,
    OrderRejectedEvent,
    OrderCancelledEvent,
    TradeExecutedEvent,
)
from .order import Order, Side, OrderType, OrderStatus
from .order_book import OrderBook
from .risk import RiskEngine
from .trade import Trade


class MatchingEngine:
    """
    Core price-time-priority matching engine.

    Responsibilities:
    - Validate incoming orders through RiskEngine
    - Reject duplicate order IDs
    - Publish deterministic engine events
    - Match LIMIT and MARKET orders
    - Maintain FIFO priority within each price level
    - Generate trades
    - Maintain order status
    - Support cancellation
    """

    def __init__(
        self,
        event_bus: EventBus | None = None,
        risk_engine: RiskEngine | None = None,
    ):
        self.books: dict[str, OrderBook] = {}

        self.next_trade_id = 1
        self.next_sequence = 1

        self.event_bus = event_bus or EventBus()
        self.risk_engine = risk_engine or RiskEngine()

    # ------------------------------------------------------------------
    # Book access
    # ------------------------------------------------------------------

    def get_book(self, symbol: str) -> OrderBook:
        book = self.books.get(symbol)

        if book is None:
            book = OrderBook(symbol)
            self.books[symbol] = book

        return book

    # ------------------------------------------------------------------
    # Event sequencing
    # ------------------------------------------------------------------

    def _next_event_sequence(self) -> int:
        sequence = self.next_sequence
        self.next_sequence += 1
        return sequence

    # ------------------------------------------------------------------
    # Order submission
    # ------------------------------------------------------------------

    def submit_order(self, order: Order) -> list[Trade]:
        """
        Submit an order to the matching engine.

        Returns all trades generated by the order.
        """

        # --------------------------------------------------------------
        # 1. Pre-trade risk validation
        # --------------------------------------------------------------

        allowed, reason = self.risk_engine.check_order(order)

        if not allowed:
            order.status = OrderStatus.REJECTED

            self.event_bus.publish(
                OrderRejectedEvent(
                    sequence=self._next_event_sequence(),
                    event_type=EventType.ORDER_REJECTED,
                    timestamp_ns=order.timestamp_ns,
                    order_id=order.order_id,
                    symbol=order.symbol,
                    reason=reason or "UNKNOWN",
                )
            )

            return []

        # --------------------------------------------------------------
        # 2. Locate/create order book
        # --------------------------------------------------------------

        book = self.get_book(order.symbol)

        # --------------------------------------------------------------
        # 3. Duplicate order ID protection
        # --------------------------------------------------------------

        if order.order_id in book.orders:
            order.status = OrderStatus.REJECTED

            self.event_bus.publish(
                OrderRejectedEvent(
                    sequence=self._next_event_sequence(),
                    event_type=EventType.ORDER_REJECTED,
                    timestamp_ns=order.timestamp_ns,
                    order_id=order.order_id,
                    symbol=order.symbol,
                    reason="DUPLICATE_ORDER_ID",
                )
            )

            return []

        # --------------------------------------------------------------
        # 4. Publish acceptance event
        #
        # Keep all metadata in the event so the event stream contains
        # enough information for recording/recovery.
        # --------------------------------------------------------------

        self.event_bus.publish(
            OrderAcceptedEvent(
                sequence=self._next_event_sequence(),
                event_type=EventType.ORDER_ACCEPTED,
                timestamp_ns=order.timestamp_ns,
                order_id=order.order_id,
                symbol=order.symbol,
                account_id=order.account_id,
                side=order.side,
                order_type=order.order_type,
                price=order.price,
                quantity=order.quantity,
            )
        )

        # --------------------------------------------------------------
        # 5. Match according to order type
        # --------------------------------------------------------------

        if order.order_type == OrderType.MARKET:
            return self._match_market(order, book)

        return self._match_limit(order, book)

    # ------------------------------------------------------------------
    # Cancellation
    # ------------------------------------------------------------------

    def cancel_order(
        self,
        symbol: str,
        order_id: int,
    ) -> bool:
        """
        Cancel a resting order.

        Returns True when an order was successfully cancelled.
        """

        book = self.books.get(symbol)

        if book is None:
            return False

        order = book.orders.get(order_id)

        if order is None:
            return False

        removed = book.remove_order(order_id)

        if not removed:
            return False

        order.status = OrderStatus.CANCELLED

        self.event_bus.publish(
            OrderCancelledEvent(
                sequence=self._next_event_sequence(),
                event_type=EventType.ORDER_CANCELLED,
                timestamp_ns=order.timestamp_ns,
                order_id=order_id,
                symbol=symbol,
            )
        )

        return True

    # ------------------------------------------------------------------
    # Trade creation
    # ------------------------------------------------------------------

    def _create_trade(
        self,
        incoming: Order,
        resting: Order,
        quantity: int,
    ) -> Trade:
        """
        Create a trade at the resting order's price.

        Price-time priority means the incoming order executes against
        the resting order at the resting order's price.
        """

        if incoming.side == Side.BUY:
            buy_order_id = incoming.order_id
            sell_order_id = resting.order_id
        else:
            buy_order_id = resting.order_id
            sell_order_id = incoming.order_id

        trade = Trade(
            trade_id=self.next_trade_id,
            symbol=incoming.symbol,
            price=resting.price,
            quantity=quantity,
            buy_order_id=buy_order_id,
            sell_order_id=sell_order_id,
        )

        self.next_trade_id += 1

        self.event_bus.publish(
            TradeExecutedEvent(
                sequence=self._next_event_sequence(),
                event_type=EventType.TRADE_EXECUTED,
                timestamp_ns=incoming.timestamp_ns,
                buy_order_id=buy_order_id,
                sell_order_id=sell_order_id,
                symbol=incoming.symbol,
                price=resting.price,
                quantity=quantity,
            )
        )

        return trade

    # ------------------------------------------------------------------
    # Fill handling
    # ------------------------------------------------------------------

    @staticmethod
    def _update_fill(
        order: Order,
        quantity: int,
    ) -> None:
        """
        Apply an execution quantity to an order.
        """

        order.filled_quantity += quantity

        if order.remaining_quantity == 0:
            order.status = OrderStatus.FILLED
        else:
            order.status = OrderStatus.PARTIALLY_FILLED

    # ------------------------------------------------------------------
    # LIMIT order matching
    # ------------------------------------------------------------------

    def _match_limit(
        self,
        order: Order,
        book: OrderBook,
    ) -> list[Trade]:
        trades: list[Trade] = []

        while order.remaining_quantity > 0:
            # Determine best opposing price
            if order.side == Side.BUY:
                best_price = book.best_ask()

                if best_price is None or best_price > order.price:
                    break

                level = book.asks[best_price]

            else:
                best_price = book.best_bid()

                if best_price is None or best_price < order.price:
                    break

                level = book.bids[best_price]

            # Cache incoming order's remaining quantity
            incoming_remaining = (
                order.quantity - order.filled_quantity
            )

            while incoming_remaining > 0:
                node = level.orders.peek()

                if node is None:
                    break

                resting_order = node.order

                # Cache resting order's remaining quantity
                resting_remaining = (
                    resting_order.quantity
                    - resting_order.filled_quantity
                )

                trade_quantity = min(
                    incoming_remaining,
                    resting_remaining,
                )

                trades.append(
                    self._create_trade(
                        incoming=order,
                        resting=resting_order,
                        quantity=trade_quantity,
                    )
                )

                order.filled_quantity += trade_quantity
                resting_order.filled_quantity += trade_quantity

                incoming_remaining -= trade_quantity

                # Update statuses
                if order.filled_quantity == order.quantity:
                    order.status = OrderStatus.FILLED
                else:
                    order.status = OrderStatus.PARTIALLY_FILLED

                if (
                    resting_order.filled_quantity
                    == resting_order.quantity
                ):
                    resting_order.status = OrderStatus.FILLED
                else:
                    resting_order.status = OrderStatus.PARTIALLY_FILLED

                # Remove fully executed resting order
                if (
                    resting_order.filled_quantity
                    == resting_order.quantity
                ):
                    book.remove_filled_order(
                        level,
                        resting_order,
                    )

            # No more liquidity at this price level
            if len(level.orders) == 0:
                continue

            # Incoming order is completely filled
            if incoming_remaining == 0:
                break

        # Remaining LIMIT quantity becomes a resting order
        if order.filled_quantity < order.quantity:
            if order.filled_quantity == 0:
                order.status = OrderStatus.OPEN
            else:
                order.status = OrderStatus.PARTIALLY_FILLED

            book.add_order(order)

        return trades
            # ------------------------------------------------------------------
    # MARKET order matching
    # ------------------------------------------------------------------

    def _match_market(
        self,
        order: Order,
        book: OrderBook,
    ) -> list[Trade]:
        """
        Match a MARKET order against the best available opposing
        liquidity.

        MARKET orders:
        - Execute against the best available prices.
        - Consume multiple price levels if necessary.
        - Never rest in the order book.
        - May be partially filled if liquidity is insufficient.
        """

        trades: list[Trade] = []

        while order.remaining_quantity > 0:

            # ----------------------------------------------------------
            # Find best opposing price
            # ----------------------------------------------------------

            if order.side == Side.BUY:
                best_price = book.best_ask()

                if best_price is None:
                    break

                level = book.asks[best_price]

            else:
                best_price = book.best_bid()

                if best_price is None:
                    break

                level = book.bids[best_price]

            # ----------------------------------------------------------
            # Match against orders at this price level
            # ----------------------------------------------------------

            incoming_remaining = (
                order.quantity - order.filled_quantity
            )

            while incoming_remaining > 0:

                node = level.orders.peek()

                if node is None:
                    break

                resting_order = node.order

                resting_remaining = (
                    resting_order.quantity
                    - resting_order.filled_quantity
                )

                trade_quantity = min(
                    incoming_remaining,
                    resting_remaining,
                )

                # ------------------------------------------------------
                # Create trade
                # ------------------------------------------------------

                trades.append(
                    self._create_trade(
                        incoming=order,
                        resting=resting_order,
                        quantity=trade_quantity,
                    )
                )

                # ------------------------------------------------------
                # Update quantities
                # ------------------------------------------------------

                order.filled_quantity += trade_quantity
                resting_order.filled_quantity += trade_quantity

                incoming_remaining -= trade_quantity

                # ------------------------------------------------------
                # Update incoming order status
                # ------------------------------------------------------

                if order.filled_quantity == order.quantity:
                    order.status = OrderStatus.FILLED
                else:
                    order.status = OrderStatus.PARTIALLY_FILLED

                # ------------------------------------------------------
                # Update resting order status
                # ------------------------------------------------------

                if (
                    resting_order.filled_quantity
                    == resting_order.quantity
                ):
                    resting_order.status = OrderStatus.FILLED
                else:
                    resting_order.status = OrderStatus.PARTIALLY_FILLED

                # ------------------------------------------------------
                # Remove completely filled resting order
                # ------------------------------------------------------

                if (
                    resting_order.filled_quantity
                    == resting_order.quantity
                ):
                    book.remove_filled_order(
                        level,
                        resting_order,
                    )

            # ----------------------------------------------------------
            # If this price level is exhausted, continue to next level
            # ----------------------------------------------------------

            if len(level.orders) == 0:
                continue

            # ----------------------------------------------------------
            # MARKET order completely filled
            # ----------------------------------------------------------

            if order.filled_quantity == order.quantity:
                break

        # --------------------------------------------------------------
        # MARKET orders NEVER rest in the order book.
        #
        # If liquidity was insufficient, the order remains partially
        # filled. If no liquidity existed, it remains OPEN.
        # --------------------------------------------------------------

        if order.filled_quantity == order.quantity:
            order.status = OrderStatus.FILLED
        elif order.filled_quantity > 0:
            order.status = OrderStatus.PARTIALLY_FILLED
        else:
            order.status = OrderStatus.OPEN

        return trades